//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abadir_buy_and_sell_app.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTable
    {
        public int indexx { get; set; }
        public string Number { get; set; }
        public string Inventory_Number { get; set; }
        public string Object_Name { get; set; }
        public string Count { get; set; }
        public string Price { get; set; }
    }
}
